profile.LOWEST=SHADOW_ENTITY=1 !FLAT_LIGHTING !ENABLE_SHADOWS
profile.LOW=profile.LOWEST shadowMapResolution=256 shadowDistance=64.0 shadowIntervalSize=7.0 SHADOW_ENTITY=-1 FLAT_LIGHTING ENABLE_SHADOWS
profile.NORMAL=profile.LOW shadowMapResolution=1024 shadowDistance=128.0 SHADOW_ENTITY=0
profile.HIGH=profile.NORMAL shadowMapResolution=4096 shadowDistance=384.0 SHADOW_ENTITY=1

screen=<profile> [LIGHTING_SCREEN] <empty> [FOG_SCREEN] <empty> [COLORS_SCREEN] <empty> [GIMMICKS_SCREEN]

screen.COLORS_SCREEN=TORCH_R TORCH_OUTER_R TORCH_G TORCH_OUTER_G TORCH_B TORCH_OUTER_B <empty> <empty> MOON_R MOON_G MOON_B
screen.FOG_SCREEN=ENABLE_FOG OVERWORLD_FOG_MIN_SLIDER <empty> OVERWORLD_FOG_MAX_SLIDER <empty> NETHER_FOG_SLIDER <empty> <empty> END_STARS_SPEED END_STARS_AMOUNT END_STARS_OPACITY
screen.LIGHTING_SCREEN=REFLECTIONS ENABLE_GODRAYS POSTERIZE_STRENGTH ENABLE_ANAGLYPH <empty> <empty> <empty> <empty> shadowDistance SUN_BRIGHTNESS shadowMapResolution SHADOW_DARKNESS shadowIntervalSize entityShadowDistanceMul SHADOW_ENTITY sunPathRotation
screen.GIMMICKS_SCREEN=HAND_DYNAMIC_LIGHTING HIGHLIGHT_WAXED GLOWING_ORES

sliders=SUN_BRIGHTNESS CONTRAST BRIGHTNESS POSTERIZE_STRENGTH SHADOW_DARKNESS WATER_B WATER_A TORCH_R TORCH_G TORCH_B TORCH_OUTER_R TORCH_OUTER_G TORCH_OUTER_B shadowDistance OVERWORLD_FOG_MIN_SLIDER OVERWORLD_FOG_MAX_SLIDER NETHER_FOG_SLIDER shadowMapResolution REFLECTIONS WATER_MIN_TEXTURE shadowIntervalSize entityShadowDistanceMul sunPathRotation MOON_R MOON_G MOON_B END_STARS_SPEED END_STARS_AMOUNT END_STARS_OPACITY

separateAo=true

oldHandLight=true

#if FLAT_LIGHTING > 0
oldLighting=false
#else
oldLighting=true
#endif

#if SHADOW_ENTITY >= 1 || (!defined IS_IRIS && SHADOW_ENTITY >= 0)
shadowEntities=true
#else
shadowEntities=false
#endif

#if SHADOW_ENTITY >= 0
shadowPlayer=true
#else
shadowPlayer=false
#endif

#ifndef IS_IRIS
program.gbuffers_clouds.enabled=false
program.gbuffers_skybasic.enabled=false
program.gbuffers_armor_glint.enabled=false
#endif